name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependencies
      working-directory: ./WhetherService
      run: dotnet restore

    - name: Build
      working-directory: ./WhetherService
      run: dotnet build --no-restore